apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.elasticsearch.version }}
  
  {{- if .Values.elasticsearch.asmCompatible }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  {{- end }}

  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.count }}
    config:
      node.store.allow_mmap: false # Fallback if vm.max_map_count isn't applied correctly
      
      {{- if .Values.elasticsearch.asmCompatible }}
      # Disable ES security. ASM mTLS handles all encryption on port 9200
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      {{- end }}
    
    podTemplate:
      metadata:
        annotations:
          {{- if .Values.elasticsearch.asmCompatible }}
          # CRITICAL for ASM: Exclude native ES traffic over 9300 from double encryption
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          {{- end }}
      spec:
        # Required for Istio sidecar validation
        automountServiceAccountToken: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage.size }}
        storageClassName: {{ .Values.elasticsearch.storage.className }}
