# Values for the qTest ECK Elasticsearch Deployment

namespace:
  name: qtest

elasticsearch:
  name: "qtest-es"
  
  # MUST be exactly 7.17.x to match Tricentis qTest requirements
  version: "7.17.23" 

  # Number of Elasticsearch nodes to deploy
  count: 3
  
  # PVC configuration for the data nodes
  storage:
    size: 50Gi
    className: "standard-rwo"

  # Whether to use ASM mTLS instead of ES internal security
  # If true, disables ES internal security so ASM can manage 
  # mTLS between nodes and from qtest-mgr.
  asmCompatible: true
